### ISSUE TITLE
Präsentationsbereitschaft herstellen

### ISSUE THREAD

**Issue by twillfade** [Nelorth/Sidescroller#26]
- Diagramme fertiggestellt?

- Testlevel frei von Spielereien?

**- Neueste Version in ein Glas gestopft?** (Jar)

**Comment by Nelorth** [comment]
## [#26] Finalizing 
Wenn ihr noch was ändern wollt, könnt ihr das **bis 21.00** Uhr;
dann compile ich nochmal alles durch und builde die `.jar` ;D

**Comment by lumpenputzer** [comment]
Vergiss nicht die Jar und auch die Source-Dateien auf nen Stick, für die anderen Knilche in unserer Klasse

**Comment by Nelorth** [comment]
Die dürfen sich die schön selber bei GitHub downloaden :P

**Comment by lumpenputzer** [comment]
Ich überlasse dann mal dir die Ehre, das letzte Issue zu closen 😄

**Comment by nkirschi** [comment]
Ich bin raus, Onkel Klaus!
